[package]
name = "chaser"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Bli-AIk/chaser"
description = "An automated file path synchronization tool that updates changed paths in configuration files in real time."

[dependencies]
notify = "8.2.0"
serde_json = "1.0.145"
serde_yaml_ng = "0.10.0"
toml = "0.9.8"
